filenamesearch: Exclude system directories
Return a failure if trying to content search the /dev, /proc or
/sys directories.

Without the exclusion for /proc you get ptrace failures in the
journal, without the exclusion for /sys the content search hangs.

In the kio-filenamesearch-grep script, the exclusions apply
if the search is from the root folder. It is only possible to
exclude directories in ripgrep by specifying a "glob", there is
no option to exclude particular directories.

The implication is that if "/proc" is excluded, all ".../proc/..."
folders are excluded.

Excluding /run would exclude user mounted devices under /run/media,
it seems not possible to exclude /run and include /run/media.

diff --git a/filenamesearch/kio-filenamesearch-grep b/filenamesearch/kio-filenamesearch-grep
--- a/filenamesearch/kio-filenamesearch-grep
+++ b/filenamesearch/kio-filenamesearch-grep
@@ -47,11 +47,22 @@ case $1 in
         # --hidden:        Don't skip hidden files and directories.
         # --no-ignore:     Don't respect .gitignore/.ignore settings.
         OPTIONS="-j2 --line-buffered -L -i --hidden --no-ignore"
+
+	# If the working drectory is root, exclude the directories "/dev", "/proc" and "/sys".
+	PWD=`pwd`
+	case $PWD in
+	    ("/dev"|"/proc"|"/sys")
+	        echo "Invalid directory:" $PWD 1>&2
+	        exit 1;;
+            ("/")
+                EXCL="--glob !/dev/ --glob !/sys/ --glob !/proc/"
+		;;
+        esac
         
         if rga --version 2>/dev/null | grep -q 'ripgrep-all'; then
-            exec rga $OPTIONS $REQUIRED_OPTIONS -e "$2" .
+            exec rga $OPTIONS $EXCL $REQUIRED_OPTIONS -e "$2" .
         elif rg --version 2>/dev/null | grep -q 'ripgrep'; then
-            exec rg $OPTIONS $REQUIRED_OPTIONS -e "$2" .
+            exec rg $OPTIONS $EXCL $REQUIRED_OPTIONS -e "$2" .
         else
             exit 127
         fi
